name: cbc
channels:
  - conda-forge
dependencies:
  - array-api-compat
  - cxx-compiler
  - h5py
  - hdf5plugin
  - jax
  - llvm-openmp
  - numpy
  - pandas
  - pybind11
  - pytables
  - python==3.10
  - scipy
  - tqdm
