name: cbc
channels:
  - conda-forge
dependencies:
  - cxx_compiler
  - fftw
  - h5py
  - hdf5plugin
  - jax
  - llvm-openmp
  - numpy
  - pandas
  - pybind11
  - pytables
  - python==3.10
  - scipy
  - tqdm
