from typing import Iterable, Iterator, List, Sequence, overload
from ..annotations import Array, BoolArray, IntArray, NDBoolArray, NDIntArray, NDRealArray

class Structure:
    """Pixel connectivity structure class. Defines a two-dimensional connectivity kernel.
    Used in peaks and streaks detection algorithms.

    Args:
        radius : Radius of connectivity kernel. The size of the kernel is (2 * radius + 1,
            2 * radius + 1).
        rank : Rank determines which elements belong to the connectivity kernel, i.e. are
            considered as neighbors of the central element. Elements up to a squared distance
            of raml from the center are considered neighbors. Rank may range from 1 (no adjacent
            elements are neighbours) to radius (all elements in (2 * radius + 1, 2 * radius + 1)
            square are neighbours).

    Attributes:
        size : Number of elements in the connectivity kernel.
        x : x indices of the connectivity kernel.
        y : y indices of the connectivity kernel.
    """
    connectivity : int
    rank : int
    shape : List[int]

    def __init__(self, radii: List[int], connectivity: int): ...

    def __iter__(self) -> Iterator[List[int]]: ...

    def __len__(self) -> int: ...

    def squeeze(self) -> 'Structure': ...

    def expand_dims(self, axis: int | Sequence[int]) -> 'Structure': ...

    def to_array(self, out: NDBoolArray | None=None) -> NDBoolArray: ...

class Region:
    @overload
    def __init__(self): ...
    @overload
    def __init__(self, index: int, structure: Structure, shape: Sequence[int]): ...

    def __iter__(self) -> Iterator[int]: ...

    def __len__(self) -> int: ...

    def __repr__(self) -> str: ...

class Regions:
    @overload
    def __init__(self): ...
    @overload
    def __init__(self, elements: Iterable[Region]): ...

    def __delitem__(self, idxs: int | slice): ...

    @overload
    def __getitem__(self, idxs: int) -> Region: ...

    @overload
    def __getitem__(self, idxs: slice) -> 'Regions': ...

    def __iter__(self) -> Iterator[Region]: ...

    def __len__(self) -> int: ...

    @overload
    def __setitem__(self, idxs: int, value: Region): ...

    @overload
    def __setitem__(self, idxs: slice, value: 'Regions'): ...

    def append(self, value: Region): ...

    def extend(self, value: 'Regions'): ...

class LabelResult:
    regions : Regions
    shape   : List[int]

    def to_mask(self, index: IntArray, out: IntArray | None = None) -> NDIntArray: ...

class Pixels2D:
    region : Region

    @overload
    def __init__(self): ...
    @overload
    def __init__(self, region: Region, data: NDRealArray): ...

    def merge(self, other: 'Pixels2D', data: NDRealArray) -> None: ...

    def total_mass(self) -> float: ...

    def mean(self) -> List[float]: ...

    def center_of_mass(self) -> List[float]: ...

    def moment_of_inertia(self) -> List[float]: ...

    def covariance_matrix(self) -> List[float]: ...

def binary_dilation(inp: BoolArray, structure: Structure, iterations: int=1,
                    mask: BoolArray | None=None, num_threads: int=1) -> NDBoolArray:
    ...

def label(inp: Array, structure: Structure, npts: int=1, num_threads: int=1) -> LabelResult:
    ...

def total_mass(labels: LabelResult, data: Array) -> NDRealArray:
    ...

def mean(labels: LabelResult, data: Array) -> NDRealArray:
    ...

def center_of_mass(labels: LabelResult, data: Array) -> NDRealArray:
    ...

def moment_of_inertia(labels: LabelResult, data: Array) -> NDRealArray:
    ...

def covariance_matrix(labels: LabelResult, data: Array) -> NDRealArray:
    ...

def line_fit(labels: LabelResult, data: Array) -> NDRealArray:
    ...
