from typing import Iterable, Iterator, List, overload
import numpy as np

class ArrayView:
    def __init__(self, array: np.ndarray): ...
    @property
    def itemsize(self) -> int: ...
    @property
    def ndim(self) -> int: ...
    @property
    def size(self) -> int: ...
    @property
    def shape(self) -> List[int]: ...
    @property
    def strides(self) -> List[int]: ...
    def __getitem__(self, index: int) -> float: ...
    def __setitem__(self, index: int, value: float) -> None: ...
    def coord_at(self, index: int) -> List[int]: ...

    @overload
    def at(self, x: int) -> float: ...
    @overload
    def at(self, y: int, x: int) -> float: ...
    @overload
    def at(self, z: int, y: int, x: int) -> float: ...
    @overload
    def at(self, coord: Iterable[int]) -> float: ...

    @overload
    def index_at(self, x: int) -> int: ...
    @overload
    def index_at(self, y: int, x: int) -> int: ...
    @overload
    def index_at(self, z: int, y: int, x: int) -> int: ...
    @overload
    def index_at(self, coord: Iterable[int]) -> int: ...

class RectangleRange:
    def __init__(self, shape: List[int]): ...
    def size(self) -> int: ...
    def __iter__(self) -> Iterator[List[int]]: ...
