from dataclasses import Field
from typing import (TYPE_CHECKING, Any, Callable, ClassVar, Dict, Generic, Iterator, List, Literal,
                    Protocol, Sequence, Tuple, Type, TypeVar, Union, cast, overload,
                    runtime_checkable)
from typing_extensions import Self
from types import ModuleType
import numpy.typing as npt
from jax import Array as JaxArray, Device as JaxDevice
import jax.numpy as jnp
import numpy as np

if TYPE_CHECKING:
    from cupy import cuda  # used only by type checkers

    class CuPyDevice(Protocol):
        attributes: Dict[str, Any]

        def __init__(self, device: 'int | CuPyDevice | None' = None) -> None: ...

        def __enter__(self) -> 'CuPyDevice': ...

        def __exit__(self, exc_type: Any, exc_value: Any, traceback: Any) -> None: ...

        def synchronize(self) -> None: ...

        def use(self) -> None: ...

    CPDevice = cast(Type[CuPyDevice], cuda.Device)
else:
    try:
        from cupy.cuda import Device as CPDevice # runtime if CuPy is installed

    except ImportError:
        CPDevice = None  # type: ignore[misc]

@runtime_checkable
class CuPyArray(Protocol):
    __cuda_array_interface__: Dict[str, Any]
    __array_priority__: float

    shape: 'Shape'
    dtype: 'DType'
    size: int
    ndim: int

    @property
    def real(self) -> 'CuPyArray': ...

    @property
    def imag(self) -> 'CuPyArray': ...

    @property
    def T(self) -> 'CuPyArray': ...

    def __float__(self) -> float: ...
    def __len__(self) -> int: ...
    def __int__(self) -> int: ...
    def __iter__(self) -> Iterator['CuPyArray']: ...
    def __getitem__(self, key: Any) -> Any: ...
    def __setitem__(self, key: Any, value: Any) -> None: ...

    def __array__(self, dtype: Any = None) -> 'NDArray': ...

    def astype(self, dtype: Any, order: str | None = 'K', casting: str = 'unsafe',
               subok: bool = True, copy: bool = True) -> 'CuPyArray': ...
    def copy(self, order: str | None = None) -> 'CuPyArray': ...
    def reshape(self, shape: 'ShapeLike', order: str = 'C') -> 'CuPyArray': ...
    def transpose(self, axes: Sequence[int] | None = None) -> 'CuPyArray': ...
    def swapaxes(self, axis1: int, axis2: int) -> 'CuPyArray': ...
    def ravel(self, order: str = 'C') -> 'CuPyArray': ...
    def flatten(self, order: str = 'C') -> 'CuPyArray': ...
    def take(self, indices: Any, axis: int | None = None,
             mode: str | None = None) -> 'CuPyArray': ...
    def sum(self, axis: 'ShapeLike | None' = None, dtype: Any = None, keepdims: bool = False
            ) -> 'CuPyArray': ...
    def mean(self, axis: 'ShapeLike | None' = None, dtype: Any = None, keepdims: bool = False
             ) -> 'CuPyArray': ...
    def min(self, axis: 'ShapeLike | None' = None, keepdims: bool = False) -> 'CuPyArray': ...
    def max(self, axis: 'ShapeLike | None' = None, keepdims: bool = False) -> 'CuPyArray': ...
    def conj(self) -> 'CuPyArray': ...
    def tolist(self) -> List[Any]: ...

    def get(self, order: Literal['C', 'F', 'A'] = 'C', out: 'NDArray | None' = None
            ) -> 'NDArray': ...

    def __add__(self, other: Any) -> 'CuPyArray': ...
    def __radd__(self, other: Any) -> 'CuPyArray': ...
    def __sub__(self, other: Any) -> 'CuPyArray': ...
    def __rsub__(self, other: Any) -> 'CuPyArray': ...
    def __mul__(self, other: Any) -> 'CuPyArray': ...
    def __rmul__(self, other: Any) -> 'CuPyArray': ...
    def __matmul__(self, other: Any) -> 'CuPyArray': ...
    def __rmatmul__(self, other: Any) -> 'CuPyArray': ...
    def __truediv__(self, other: Any) -> 'CuPyArray': ...
    def __rtruediv__(self, other: Any) -> 'CuPyArray': ...
    def __floordiv__(self, other: Any) -> 'CuPyArray': ...
    def __rfloordiv__(self, other: Any) -> 'CuPyArray': ...
    def __mod__(self, other: Any) -> 'CuPyArray': ...
    def __rmod__(self, other: Any) -> 'CuPyArray': ...
    def __divmod__(self, other: Any) -> Tuple['CuPyArray', 'CuPyArray']: ...
    def __rdivmod__(self, other: Any) -> 'CuPyArray': ...
    def __pow__(self, other: Any) -> 'CuPyArray': ...
    def __rpow__(self, other: Any) -> 'CuPyArray': ...
    def __neg__(self) -> 'CuPyArray': ...
    def __pos__(self) -> 'CuPyArray': ...
    def __abs__(self) -> 'CuPyArray': ...

    def __and__(self, other: Any) -> 'CuPyArray': ...
    def __rand__(self, other: Any) -> 'CuPyArray': ...
    def __or__(self, other: Any) -> 'CuPyArray': ...
    def __ror__(self, other: Any) -> 'CuPyArray': ...
    def __xor__(self, other: Any) -> 'CuPyArray': ...
    def __rxor__(self, other: Any) -> 'CuPyArray': ...

    def __eq__(self, other: Any) -> 'CuPyArray': ...
    def __ne__(self, other: Any) -> 'CuPyArray': ...
    def __lt__(self, other: Any) -> 'CuPyArray': ...
    def __le__(self, other: Any) -> 'CuPyArray': ...
    def __gt__(self, other: Any) -> 'CuPyArray': ...
    def __ge__(self, other: Any) -> 'CuPyArray': ...

    def __repr__(self) -> str: ...

T = TypeVar('T')
T_Array = TypeVar('T_Array', bound='Array')

FileMode = Literal['r', 'r+', 'w', 'w-', 'x', 'a']
Attribute = str | Literal['data', 'eigen_field', 'eigen_value', 'flatfield', 'mask', 'std', 'snr', 'whitefield', 'whitefields']

PyTree = Any
Scalar = int | float | np.bool_ | np.number | bool | complex
Shape = Tuple[int, ...]
IntTuple = Tuple[int, ...]
FloatTuple = Tuple[float, ...]

GenericAlias = type(list[int]) | type(List[int])
UnionType = type(int | list) | type(Union[int, list])
AnyType = Type | GenericAlias | UnionType | str | Any
ExpandedType = AnyType | Tuple[AnyType, List]

ArrayDevice = JaxDevice | CPDevice | Literal['cpu']

DType = np.dtype
DTypeLike = Union[
    str,                # like 'float32', 'int32'
    type[Any],          # like np.float32, np.int32, float, int
    DType,              # like np.dtype('float32'), np.dtype('int32')
    'SupportsDType',    # like xp.float32, xp.int32
]

CPArray = CuPyArray
CPBoolArray = CuPyArray
CPComplexArray = CuPyArray
CPIntArray = CuPyArray
CPRealArray = CuPyArray

JaxBoolArray = JaxArray
JaxComplexArray = JaxArray
JaxIntArray = JaxArray
JaxRealArray = JaxArray

NDArray = np.ndarray
NDArrayLike = npt.ArrayLike
NDBoolArray = npt.NDArray[np.bool_]
NDComplexArray = npt.NDArray[np.floating[Any] | np.complexfloating[Any, Any]]
NDIntArray = npt.NDArray[np.integer[Any]]
NDRealArray = npt.NDArray[np.floating[Any]]

ArrayLike = JaxArray | NDArray | CPArray | Scalar | Sequence
Array = JaxArray | NDArray | CPArray
BoolArray = JaxBoolArray | NDBoolArray | CPBoolArray
ComplexArray = JaxComplexArray | NDComplexArray | CPComplexArray
IntArray = JaxIntArray | NDIntArray | CPIntArray
RealArray = JaxRealArray | NDRealArray | CPRealArray

Indices = int | slice | IntArray | Sequence[int]
MultiIndices = Indices | Tuple[Indices, ...]

IntSequence = int | np.integer[Any] | Sequence[int] | IntArray
RealSequence = float | np.floating[Any] | Sequence[float] | RealArray
ROI = List[int] | Tuple[int, int, int, int] | IntArray

AnyFloat = float | np.floating[Any] | RealArray
ShapeLike = int | np.integer[Any] | Sequence[int] | IntArray

class ReferenceType(Generic[T]):
    __callback__: Callable[['ReferenceType[T]'], Any]

    def __new__(cls: Type[Self], o: T,
                callback: Callable[['ReferenceType[T]'], Any] | None=...) -> Self: ...

    def __call__(self) -> T: ...

@runtime_checkable
class SupportsNamespace(Protocol):
    def __array_namespace__(self) -> 'ModuleType | ArrayNamespace': ...

@runtime_checkable
class DataclassInstance(Protocol):
    __dataclass_fields__: ClassVar[Dict[str, Field[Any]]]

@runtime_checkable
class SupportsDType(Protocol):
    @property
    def dtype(self) -> DType: ...

class Generator(Generic[T_Array], Protocol):
    def beta(self, a: AnyFloat, b: AnyFloat, size: ShapeLike | None = None) -> T_Array: ...

    def binomial(self, n: IntSequence, p: AnyFloat, size: ShapeLike | None = None) -> T_Array: ...

    def chisquare(self, df: AnyFloat, size: ShapeLike | None = None) -> T_Array: ...

    def choice(self, a: int | IntSequence | RealSequence | ArrayLike, size: ShapeLike | None = None,
               replace: bool = True, p: RealSequence | ArrayLike | None = None) -> T_Array: ...

    def dirichlet(self, alpha: RealSequence, size: ShapeLike | None = None) -> T_Array: ...

    def exponential(self, scale: AnyFloat = 1.0, size: ShapeLike | None = None) -> T_Array: ...

    def f(self, dfnum: AnyFloat, dfden: AnyFloat, size: ShapeLike | None = None) -> T_Array: ...

    def gamma(self, shape: AnyFloat, scale: AnyFloat = 1.0, size: ShapeLike | None = None
              ) -> T_Array: ...

    def geometric(self, p: AnyFloat, size: ShapeLike | None = None) -> T_Array: ...

    def integers(self, low: IntSequence, high: IntSequence | None = None,
                 size: ShapeLike | None = None, dtype: DTypeLike = np.int64) -> T_Array: ...

    def laplace(self, loc: AnyFloat = 0.0, scale: AnyFloat = 1.0,
                size: ShapeLike | None = None) -> T_Array: ...

    def logistic(self, loc: AnyFloat = 0.0, scale: AnyFloat = 1.0,
                 size: ShapeLike | None = None) -> T_Array: ...

    def lognormal(self, mean: AnyFloat = 0.0, sigma: AnyFloat = 1.0,
                  size: ShapeLike | None = None) -> T_Array: ...

    def multivariate_normal(self, mean: RealSequence, cov: ArrayLike,
                            size: ShapeLike | None = None) -> T_Array: ...

    def normal(self, loc: AnyFloat = 0.0, scale: AnyFloat = 1.0,
               size: ShapeLike | None = None) -> T_Array: ...

    def pareto(self, a: AnyFloat, size: ShapeLike | None = None) -> T_Array: ...

    def permutation(self, x: IntSequence | RealSequence | ArrayLike) -> T_Array: ...

    def poisson(self, lam: AnyFloat = 1.0, size: ShapeLike | None = None) -> T_Array: ...

    def random(self, size: ShapeLike | None = None, dtype: DTypeLike = np.float64
               ) -> T_Array: ...

    def rayleigh(self, scale: AnyFloat = 1.0, size: ShapeLike | None = None) -> T_Array: ...

    def standard_exponential(self, size: ShapeLike | None = None, dtype: DTypeLike = np.float64
                             ) -> T_Array: ...

    def standard_gamma(self, shape: AnyFloat, size: ShapeLike | None = None,
                       dtype: DTypeLike = np.float64) -> T_Array: ...

    def standard_normal(self, size: ShapeLike | None = None, dtype: DTypeLike = np.float64
                        ) -> T_Array: ...

    def uniform(self, low: AnyFloat = 0.0, high: AnyFloat = 1.0, size: ShapeLike | None = None
                ) -> T_Array: ...

class LinalgNamespace(Generic[T_Array]):
    """Linear Algebra Extension namespace providing matrix and vector operations."""

    def cholesky(self, x: ArrayLike, /, *, upper: bool = False) -> T_Array: ...

    def cross(self, x1: ArrayLike, x2: ArrayLike, /, *, axis: int = -1) -> T_Array: ...

    def det(self, x: ArrayLike, /) -> T_Array: ...

    def diagonal(self, x: ArrayLike, /, *, offset: int = 0) -> T_Array: ...

    def eigh(self, x: ArrayLike, /) -> Tuple[T_Array, T_Array]: ...

    def eigvalsh(self, x: ArrayLike, /) -> T_Array: ...

    def inv(self, x: ArrayLike, /) -> T_Array: ...

    def matmul(self, x1: ArrayLike, x2: ArrayLike, /) -> T_Array: ...

    def matrix_norm(self, x: ArrayLike, /, *, keepdims: bool = False,
                    ord: int | float | Literal['fro', 'nuc'] | None = 'fro') -> T_Array: ...

    def matrix_power(self, x: ArrayLike, n: int, /) -> T_Array: ...

    def matrix_rank(self, x: ArrayLike, /, *, rtol: float | ArrayLike | None = None
                    ) -> T_Array: ...

    def matrix_transpose(self, x: ArrayLike, /) -> T_Array: ...

    def outer(self, x1: ArrayLike, x2: ArrayLike, /) -> T_Array: ...

    def pinv(self, x: ArrayLike, /, *, rtol: float | ArrayLike | None = None) -> T_Array: ...

    def qr(self, x: ArrayLike, /, *, mode: Literal['reduced', 'complete'] = 'reduced'
           ) -> Tuple[T_Array, T_Array]: ...

    def slogdet(self, x: ArrayLike, /) -> Tuple[T_Array, T_Array]: ...

    def solve(self, x1: ArrayLike, x2: ArrayLike, /) -> T_Array: ...

    def svd(self, x: ArrayLike, /, *, full_matrices: bool = True
            ) -> Tuple[T_Array, T_Array, T_Array]: ...

    def svdvals(self, x: ArrayLike, /) -> T_Array: ...

    def tensordot(self, x1: ArrayLike, x2: ArrayLike, /, *,
                  axes: int | Tuple[Sequence[int], Sequence[int]] = 2) -> T_Array: ...

    def trace(self, x: ArrayLike, /, *, offset: int = 0,
              dtype: DTypeLike | None = None) -> T_Array: ...

    def vecdot(self, x1: ArrayLike, x2: ArrayLike, /, *, axis: int = -1) -> T_Array: ...

    def vector_norm(self, x: ArrayLike, /, *, axis: int | Tuple[int, ...] | None = None,
                    keepdims: bool = False, ord: int | float = 2) -> T_Array: ...

class FFTNamespace(Generic[T_Array]):
    """Fourier Transform Extension namespace providing FFT operations."""

    def fft(self, x: ArrayLike, /, *, n: int | None = None, axis: int = -1,
            norm: Literal['backward', 'ortho', 'forward'] = 'backward') -> T_Array: ...

    def ifft(self, x: ArrayLike, /, *, n: int | None = None, axis: int = -1,
             norm: Literal['backward', 'ortho', 'forward'] = 'backward') -> T_Array: ...

    def rfft(self, x: ArrayLike, /, *, n: int | None = None, axis: int = -1,
             norm: Literal['backward', 'ortho', 'forward'] = 'backward') -> T_Array: ...

    def irfft(self, x: ArrayLike, /, *, n: int | None = None, axis: int = -1,
              norm: Literal['backward', 'ortho', 'forward'] = 'backward') -> T_Array: ...

    def hfft(self, x: ArrayLike, /, *, n: int | None = None, axis: int = -1,
             norm: Literal['backward', 'ortho', 'forward'] = 'backward') -> T_Array: ...

    def ihfft(self, x: ArrayLike, /, *, n: int | None = None, axis: int = -1,
              norm: Literal['backward', 'ortho', 'forward'] = 'backward') -> T_Array: ...

    def fftn(self, x: ArrayLike, /, *, s: Sequence[int] | None = None,
             axes: Sequence[int] | None = None,
             norm: Literal['backward', 'ortho', 'forward'] = 'backward') -> T_Array: ...

    def ifftn(self, x: ArrayLike, /, *, s: Sequence[int] | None = None,
              axes: Sequence[int] | None = None,
              norm: Literal['backward', 'ortho', 'forward'] = 'backward') -> T_Array: ...

    def rfftn(self, x: ArrayLike, /, *, s: Sequence[int] | None = None,
              axes: Sequence[int] | None = None,
              norm: Literal['backward', 'ortho', 'forward'] = 'backward') -> T_Array: ...

    def irfftn(self, x: ArrayLike, /, *, s: Sequence[int] | None = None,
               axes: Sequence[int] | None = None,
               norm: Literal['backward', 'ortho', 'forward'] = 'backward') -> T_Array: ...

    def fftfreq(self, n: int, /, *, d: float = 1.0,
                device: ArrayDevice | None = None) -> T_Array: ...

    def rfftfreq(self, n: int, /, *, d: float = 1.0,
                 device: ArrayDevice | None = None) -> T_Array: ...

    def fftshift(self, x: ArrayLike, /, *, axes: ShapeLike | None = None) -> T_Array: ...

    def ifftshift(self, x: ArrayLike, /, *, axes: ShapeLike | None = None) -> T_Array: ...

class OGridClass(Generic[T_Array]):
    def __getitem__(self, key: slice | Sequence[slice]) -> Tuple[T_Array, ...]: ...

class MGridClass(Generic[T_Array]):
    def __getitem__(self, key: slice | Sequence[slice]) -> T_Array: ...

class ArrayNamespace(Generic[T_Array]):
    uint4   = int
    uint8   = int
    uint16  = int
    uint32  = int
    uint64  = int
    int4    = int
    int8    = int
    int16   = int
    int32   = int
    int64   = int
    float8  = float
    float16 = float
    float32 = single = float
    float64 = double = float
    complex64 = csingle = complex
    complex128 = cdouble = complex

    inf     : float
    nan     : float
    pi      : float
    e       : float

    ogrid   : OGridClass
    mgrid   : MGridClass

    linalg  : LinalgNamespace[T_Array]
    fft     : FFTNamespace[T_Array]

    def dtype(self, type: DTypeLike) -> DType: ...

    def __getattr__(self, name: str) -> Callable[[Any], Any | T_Array]: ...

    # ========== Creation Functions ==========

    def arange(self, start: ArrayLike | int, /, stop: ArrayLike | int | None = None,
               step: ArrayLike | int | None = None, *, dtype: DTypeLike | None = None,
               device: ArrayDevice | None = None) -> T_Array: ...

    def asarray(self, obj: Any, /, *, dtype: DTypeLike | None = None,
                device: ArrayDevice | None = None, copy: bool | None = None) -> T_Array: ...

    def empty(self, shape: ShapeLike, /, *, dtype: DTypeLike | None = None,
              device: ArrayDevice | None = None) -> T_Array: ...

    def empty_like(self, x: ArrayLike, /, *, dtype: DTypeLike | None = None,
                   device: ArrayDevice | None = None) -> T_Array: ...

    def eye(self, n_rows: int, n_cols: int | None = None, /, *, k: int = 0,
            dtype: DTypeLike | None = None, device: ArrayDevice | None = None
            ) -> T_Array: ...

    def from_dlpack(self, x: Any, /) -> T_Array: ...

    def full(self, shape: ShapeLike, fill_value: ArrayLike, /, *,
             dtype: DTypeLike | None = None, device: ArrayDevice | None = None
             ) -> T_Array: ...

    def full_like(self, x: ArrayLike, fill_value: ArrayLike, /, *,
                  dtype: DTypeLike | None = None, device: ArrayDevice | None = None
                  ) -> T_Array: ...

    def linspace(self, start: ArrayLike, stop: ArrayLike, /, num: int = 50,
                 *, dtype: DTypeLike | None = None, device: ArrayDevice | None = None,
                 endpoint: bool = True) -> T_Array: ...

    def meshgrid(self, *xs: ArrayLike, indexing: str = 'xy') -> list[T_Array]: ...

    def ones(self, shape: ShapeLike, /, *, dtype: DTypeLike | None = None,
             device: ArrayDevice | None = None) -> T_Array: ...

    def ones_like(self, x: ArrayLike, /, *, dtype: DTypeLike | None = None,
                  device: ArrayDevice | None = None) -> T_Array: ...

    def tril(self, x: ArrayLike, /, *, k: int = 0) -> T_Array: ...

    def triu(self, x: ArrayLike, /, *, k: int = 0) -> T_Array: ...

    def zeros(self, shape: ShapeLike, /, *, dtype: DTypeLike | None = None,
              device: ArrayDevice | None = None) -> T_Array: ...

    def zeros_like(self, x: ArrayLike, /, *, dtype: DTypeLike | None = None,
                   device: ArrayDevice | None = None) -> T_Array: ...

    # ========== Data Type Functions ==========

    def astype(self, x: ArrayLike, dtype: DTypeLike, /, *, copy: bool = True) -> T_Array: ...

    def can_cast(self, from_: DTypeLike | ArrayLike, to: DTypeLike, /) -> bool: ...

    def finfo(self, type: DTypeLike, /) -> Any: ...

    def iinfo(self, type: DTypeLike, /) -> Any: ...

    def isdtype(self, dtype: DTypeLike, /, kind: str | Tuple[str, ...] | None = None
                ) -> bool: ...

    def result_type(self, *arrays_and_dtypes: ArrayLike | DTypeLike) -> DTypeLike: ...

    # ========== Element-wise Functions ==========

    def abs(self, x: ArrayLike, /) -> T_Array: ...

    def acos(self, x: ArrayLike, /) -> T_Array: ...

    def acosh(self, x: ArrayLike, /) -> T_Array: ...

    def add(self, x1: ArrayLike, x2: ArrayLike, /) -> T_Array: ...

    def asin(self, x: ArrayLike, /) -> T_Array: ...

    def asinh(self, x: ArrayLike, /) -> T_Array: ...

    def atan(self, x: ArrayLike, /) -> T_Array: ...

    def atan2(self, x1: ArrayLike, x2: ArrayLike, /) -> T_Array: ...

    def atanh(self, x: ArrayLike, /) -> T_Array: ...

    def bitwise_and(self, x1: ArrayLike, x2: ArrayLike, /) -> T_Array: ...

    def bitwise_left_shift(self, x1: ArrayLike, x2: ArrayLike, /) -> T_Array: ...

    def bitwise_invert(self, x: ArrayLike, /) -> T_Array: ...

    def bitwise_or(self, x1: ArrayLike, x2: ArrayLike, /) -> T_Array: ...

    def bitwise_right_shift(self, x1: ArrayLike, x2: ArrayLike, /) -> T_Array: ...

    def bitwise_xor(self, x1: ArrayLike, x2: ArrayLike, /) -> T_Array: ...

    def ceil(self, x: ArrayLike, /) -> T_Array: ...

    def clip(self, x: ArrayLike, /, x_min: ArrayLike | None = None,
             x_max: ArrayLike | None = None) -> T_Array: ...

    def conj(self, x: ArrayLike, /) -> T_Array: ...

    def copysign(self, x1: ArrayLike, x2: ArrayLike, /) -> T_Array: ...

    def cos(self, x: ArrayLike, /) -> T_Array: ...

    def cosh(self, x: ArrayLike, /) -> T_Array: ...

    def divide(self, x1: ArrayLike, x2: ArrayLike, /) -> T_Array: ...

    def equal(self, x1: ArrayLike, x2: ArrayLike, /) -> T_Array: ...

    def exp(self, x: ArrayLike, /) -> T_Array: ...

    def expm1(self, x: ArrayLike, /) -> T_Array: ...

    def floor(self, x: ArrayLike, /) -> T_Array: ...

    def floor_divide(self, x1: ArrayLike, x2: ArrayLike, /) -> T_Array: ...

    def greater(self, x1: ArrayLike, x2: ArrayLike, /) -> T_Array: ...

    def greater_equal(self, x1: ArrayLike, x2: ArrayLike, /) -> T_Array: ...

    def hypot(self, x1: ArrayLike, x2: ArrayLike, /) -> T_Array: ...

    def imag(self, x: ArrayLike, /) -> T_Array: ...

    def isfinite(self, x: ArrayLike, /) -> T_Array: ...

    def isinf(self, x: ArrayLike, /) -> T_Array: ...

    def isnan(self, x: ArrayLike, /) -> T_Array: ...

    def less(self, x1: ArrayLike, x2: ArrayLike, /) -> T_Array: ...

    def less_equal(self, x1: ArrayLike, x2: ArrayLike, /) -> T_Array: ...

    def log(self, x: ArrayLike, /) -> T_Array: ...

    def log1p(self, x: ArrayLike, /) -> T_Array: ...

    def log2(self, x: ArrayLike, /) -> T_Array: ...

    def log10(self, x: ArrayLike, /) -> T_Array: ...

    def logaddexp(self, x1: ArrayLike, x2: ArrayLike, /) -> T_Array: ...

    def logical_and(self, x1: ArrayLike, x2: ArrayLike, /) -> T_Array: ...

    def logical_not(self, x: ArrayLike, /) -> T_Array: ...

    def logical_or(self, x1: ArrayLike, x2: ArrayLike, /) -> T_Array: ...

    def logical_xor(self, x1: ArrayLike, x2: ArrayLike, /) -> T_Array: ...

    def maximum(self, x1: ArrayLike, x2: ArrayLike, /) -> T_Array: ...

    def minimum(self, x1: ArrayLike, x2: ArrayLike, /) -> T_Array: ...

    def multiply(self, x1: ArrayLike, x2: ArrayLike, /) -> T_Array: ...

    def negative(self, x: ArrayLike, /) -> T_Array: ...

    def nextafter(self, x1: ArrayLike, x2: ArrayLike, /) -> T_Array: ...

    def not_equal(self, x1: ArrayLike, x2: ArrayLike, /) -> T_Array: ...

    def positive(self, x: ArrayLike, /) -> T_Array: ...

    def pow(self, x1: ArrayLike, x2: ArrayLike, /) -> T_Array: ...

    def real(self, x: ArrayLike, /) -> T_Array: ...

    def reciprocal(self, x: ArrayLike, /) -> T_Array: ...

    def remainder(self, x1: ArrayLike, x2: ArrayLike, /) -> T_Array: ...

    def round(self, x: ArrayLike, /) -> T_Array: ...

    def sign(self, x: ArrayLike, /) -> T_Array: ...

    def signbit(self, x: ArrayLike, /) -> T_Array: ...

    def sin(self, x: ArrayLike, /) -> T_Array: ...

    def sinh(self, x: ArrayLike, /) -> T_Array: ...

    def square(self, x: ArrayLike, /) -> T_Array: ...

    def sqrt(self, x: ArrayLike, /) -> T_Array: ...

    def subtract(self, x1: ArrayLike, x2: ArrayLike, /) -> T_Array: ...

    def tan(self, x: ArrayLike, /) -> T_Array: ...

    def tanh(self, x: ArrayLike, /) -> T_Array: ...

    def trunc(self, x: ArrayLike, /) -> T_Array: ...

    # ========== Indexing Functions ==========

    def take(self, x: ArrayLike, indices: ArrayLike, /, *, axis: int | None = None,
             mode: str = 'clip') -> T_Array: ...

    def take_along_axis(self, arr: ArrayLike, indices: ArrayLike, /, axis: int) -> T_Array: ...

    def unravel_index(self, indices: ArrayLike, shape: ShapeLike, /) -> Tuple[T_Array, ...]: ...

    # ========== Linear Algebra Functions ==========

    def matmul(self, x1: ArrayLike, x2: ArrayLike, /) -> T_Array: ...

    def matrix_transpose(self, x: ArrayLike, /) -> T_Array: ...

    def tensordot(self, x1: ArrayLike, x2: ArrayLike, /, axes: int | Sequence[int] |
                  Sequence[Sequence[int]] = 2) -> T_Array: ...

    def vecdot(self, x1: ArrayLike, x2: ArrayLike, /, *, axis: int = -1) -> T_Array: ...

    # ========== Manipulation Functions ==========

    def broadcast_arrays(self, *arrays: ArrayLike) -> list[T_Array]: ...

    def broadcast_to(self, x: ArrayLike, /, shape: ShapeLike) -> T_Array: ...

    def concat(self, xs: Sequence[ArrayLike], /, axis: int | None = 0) -> T_Array: ...

    def expand_dims(self, x: ArrayLike, /, axis: int = 0) -> T_Array: ...

    def flip(self, m: ArrayLike, /, axis: ShapeLike | None = None) -> T_Array: ...

    def moveaxis(self, x: ArrayLike, source: ShapeLike,
                 destination: ShapeLike, /) -> T_Array: ...

    def permute_dims(self, x: ArrayLike, /, axes: Sequence[int]) -> T_Array: ...

    def repeat(self, x: ArrayLike, repeats: int | ArrayLike, /, *, axis: int | None = None
               ) -> T_Array: ...

    def reshape(self, x: ArrayLike, /, shape: ShapeLike, copy: bool | None = None
                ) -> T_Array: ...

    def roll(self, x: ArrayLike, /, shift: ShapeLike, *,
             axis: ShapeLike | None = None) -> T_Array: ...

    def squeeze(self, x: ArrayLike, /, axis: ShapeLike | None = None
                ) -> T_Array: ...

    def stack(self, xs: Sequence[ArrayLike], /, axis: int = 0) -> T_Array: ...

    def tile(self, x: ArrayLike, reps: int | Sequence[int], /) -> T_Array: ...

    def unstack(self, x: ArrayLike, /, *, axis: int = 0) -> list[T_Array]: ...

    # ========== Searching Functions ==========

    def argmax(self, x: ArrayLike, /, axis: int | None = None, keepdims: bool = False
               ) -> T_Array: ...

    def argmin(self, x: ArrayLike, /, axis: int | None = None, keepdims: bool = False
               ) -> T_Array: ...

    def count_nonzero(self, x: ArrayLike, /, axis: ShapeLike | None = None
                      ) -> T_Array: ...

    def nonzero(self, x: ArrayLike, /) -> Tuple[T_Array, ...]: ...

    def searchsorted(self, x1: ArrayLike, x2: ArrayLike, /, side: str = 'left',
                     sorter: ArrayLike | None = None) -> T_Array: ...

    @overload
    def where(self, condition: ArrayLike, /) -> Tuple[T_Array, ...]: ...

    @overload
    def where(self, condition: ArrayLike, x1: ArrayLike, x2: ArrayLike, /) -> T_Array: ...

    def where(self, condition: ArrayLike, x1: ArrayLike | None = None,
              x2: ArrayLike | None = None, /) -> T_Array | Tuple[T_Array, ...]: ...

    # ========== Set Functions ==========

    def unique_all(self, x: ArrayLike, /
                   ) -> Tuple[T_Array, T_Array, T_Array, T_Array]: ...

    def unique_counts(self, x: ArrayLike, /) -> Tuple[T_Array, T_Array]: ...

    def unique_inverse(self, x: ArrayLike, /) -> Tuple[T_Array, T_Array]: ...

    def unique_values(self, x: ArrayLike, /) -> T_Array: ...

    # ========== Sorting Functions ==========

    def argpartition(self, x: ArrayLike, kth: int | Sequence[int], /, axis: int = -1
                     ) -> T_Array: ...

    def argsort(self, x: ArrayLike, /, axis: int = -1, descending: bool = False,
                stable: bool = True) -> T_Array: ...

    def partition(self, x: ArrayLike, kth: int | Sequence[int], /, axis: int = -1
                  ) -> T_Array: ...

    def sort(self, x: ArrayLike, /, axis: int = -1, descending: bool = False,
             stable: bool = True) -> T_Array: ...

    # ========== Statistical Functions ==========

    def cumulative_prod(self, x: ArrayLike, /, axis: int | None = None,
                        dtype: DTypeLike | None = None, include_initial: bool = False
                        ) -> T_Array: ...

    def cumulative_sum(self, x: ArrayLike, /, axis: int | None = None,
                       dtype: DTypeLike | None = None, include_initial: bool = False
                       ) -> T_Array: ...

    def max(self, x: ArrayLike, /, axis: ShapeLike | None = None,
            keepdims: bool = False) -> T_Array: ...

    def mean(self, x: ArrayLike, /, axis: ShapeLike | None = None,
             keepdims: bool = False) -> T_Array: ...

    def median(self, x: ArrayLike, /, axis: ShapeLike | None = None,
               overwrite_input: bool = False, keepdims: bool = False) -> T_Array: ...

    def nanmedian(self, x: ArrayLike, /, axis: ShapeLike | None = None,
                  overwrite_input: bool = False, keepdims: bool = False) -> T_Array: ...

    def min(self, x: ArrayLike, /, axis: ShapeLike | None = None,
            keepdims: bool = False) -> T_Array: ...

    def prod(self, x: ArrayLike, /, axis: ShapeLike | None = None,
             dtype: DTypeLike | None = None, keepdims: bool = False) -> T_Array: ...

    def std(self, x: ArrayLike, /, axis: ShapeLike | None = None,
            correction: int | float = 0.0, keepdims: bool = False) -> T_Array: ...

    def sum(self, x: ArrayLike, /, axis: ShapeLike | None = None,
            dtype: DTypeLike | None = None, keepdims: bool = False) -> T_Array: ...

    def var(self, x: ArrayLike, /, axis: ShapeLike | None = None,
            correction: int | float = 0.0, keepdims: bool = False) -> T_Array: ...

    # ========== Utility Functions ==========

    def all(self, x: ArrayLike, /, axis: ShapeLike | None = None,
            keepdims: bool = False) -> T_Array: ...

    def any(self, x: ArrayLike, /, axis: ShapeLike | None = None,
            keepdims: bool = False) -> T_Array: ...

    def diff(self, x: ArrayLike, /, n: int = 1, axis: int = -1,
             prepend: ArrayLike | None = None, append: ArrayLike | None = None
             ) -> T_Array: ...

    # ========== Extra Functions not in Array API ==========

    def fromstring(self, string: str, dtype: DTypeLike=float, count: int=-1, *,
                   sep: str | None = None) -> T_Array: ...

    def array(self, object: Any, /, *, dtype: DTypeLike | None = None,
              device: ArrayDevice | None = None, copy: bool | None = None) -> T_Array: ...

    def insert(self, arr: ArrayLike, obj: ArrayLike | int, values: ArrayLike, /,
               axis: int | None = None) -> T_Array: ...

    def isclose(self, x1: ArrayLike, x2: ArrayLike, /, rtol: float = 1e-05,
                atol: float = 1e-08, equal_nan: bool = False) -> T_Array: ...

    def allclose(self, x1: ArrayLike, x2: ArrayLike, /, rtol: float = 1e-05,
                 atol: float = 1e-08, equal_nan: bool = False) -> bool: ...

    def invert(self, x: ArrayLike, /) -> T_Array: ...

    def lexsort(self, x: ArrayLike, /, axis: int = -1) -> T_Array: ...

    def ravel_multi_index(self, multi_index: ArrayLike, dims: ShapeLike, /,
                          mode: Literal['raise', 'wrap', 'clip'] = 'raise') -> T_Array: ...

    @overload
    def unique(self, x: ArrayLike, /, *, return_index: Literal[False] = False,
               return_inverse: Literal[False] = False, return_counts: Literal[False] = False,
               axis: int | None = None, equal_nan: bool = False) -> T_Array: ...

    @overload
    def unique(self, x: ArrayLike, /, *, return_index: Literal[True],
               return_inverse: Literal[False] = False, return_counts: Literal[False] = False,
               axis: int | None = None, equal_nan: bool = False) -> Tuple[T_Array, T_Array]: ...

    @overload
    def unique(self, x: ArrayLike, /, *, return_index: Literal[False] = False,
               return_inverse: Literal[True], return_counts: Literal[False] = False,
               axis: int | None = None, equal_nan: bool = False) -> Tuple[T_Array, T_Array]: ...

    @overload
    def unique(self, x: ArrayLike, /, *, return_index: Literal[False] = False,
               return_inverse: Literal[False] = False, return_counts: Literal[True],
               axis: int | None = None, equal_nan: bool = False) -> Tuple[T_Array, T_Array]: ...

    @overload
    def unique(self, x: ArrayLike, /, *, return_index: Literal[True],
               return_inverse: Literal[True], return_counts: Literal[False] = False,
               axis: int | None = None, equal_nan: bool = False
               ) -> Tuple[T_Array, T_Array, T_Array]: ...

    @overload
    def unique(self, x: ArrayLike, /, *, return_index: Literal[True],
               return_inverse: Literal[False] = False, return_counts: Literal[True],
               axis: int | None = None, equal_nan: bool = False
               ) -> Tuple[T_Array, T_Array, T_Array]: ...

    @overload
    def unique(self, x: ArrayLike, /, *, return_index: Literal[False] = False,
               return_inverse: Literal[True], return_counts: Literal[True],
               axis: int | None = None, equal_nan: bool = False
               ) -> Tuple[T_Array, T_Array, T_Array]: ...

    @overload
    def unique(self, x: ArrayLike, /, *, return_index: Literal[True],
               return_inverse: Literal[True], return_counts: Literal[True],
               axis: int | None = None, equal_nan: bool = False
               ) -> Tuple[T_Array, T_Array, T_Array, T_Array]: ...

    def unique(self, x: ArrayLike, /, *, return_index: bool = False,
               return_inverse: bool = False, return_counts: bool = False,
               axis: int | None = None, equal_nan: bool = False
               ) -> T_Array | Tuple[T_Array, ...]: ...

JaxNumPy = cast(ArrayNamespace[JaxArray], jnp)
NumPy = cast(ArrayNamespace[NDArray], np)

try:
    from array_api_compat import cupy as cp

    CuPy = cast(ArrayNamespace[CuPyArray], cp)
except ImportError:
    CuPy = None

NumPyNamespace = ArrayNamespace[NDArray]
JaxNamespace = ArrayNamespace[JaxArray]
CuPyNamespace = ArrayNamespace[CuPyArray]

AnyGenerator = Generator[CPArray] | Generator[JaxArray] | Generator[NDArray]
AnyNamespace = CuPyNamespace | JaxNamespace | NumPyNamespace
